repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false
