name: Linters

on: push
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run ruff
        run: |
          source .venv/bin/activate
          uv run inv linter

      - name: Run mypy
        run: |
          source .venv/bin/activate
          uv run inv types