name: Linters + Unit Tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run ruff
        run: |
          source .venv/bin/activate
          uv run inv check

      - name: Run tests
        run: |
          source .venv/bin/activate
          uv run inv tests
