name: Unit Tests

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync uv
        run: uv sync

      - name: Run tests
        run: |
          .venv/bin/activate
          uv run inv tests
